<?php
$title = 'Location voiture';
$this->headTitle($title);
 ?>
 <h1 class="title"><?php echo $this->escapeHtml($title); ?></h1>
 <a href = "<?php echo $this->url('login/process', array('action' => 'logout')); ?>">Logout</a>
 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Ajouter une nouvelle voiture</a>
 </p>

 <table class="table">
 <tr>
     <th>Photo</th>
     <th>Modèle</th>
     <th>Marque</th>
     <th>Année</th>
     <th>Prix/jour</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->title);?></td>
     <td><?php echo $this->escapeHtml($album->artist);?></td>
     <td>
         <a href="<?php echo $this->url('album',
             array('action'=>'edit', 'id' => $album->id));?>">Modifier</a>
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $album->id));?>">Supprimer</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>